development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://aepofgjtshpyoj:lsKg_JbA3X7NiLZ2ehCyrmd7n0@ec2-54-243-200-159.compute-1.amazonaws.com:5432/d3cf5ouk9llqt3
